if(UNIX AND NOT APPLE)
    set(LINUX TRUE)
    set(PLATFORM_ENV "linux")
else()
    set(LINUX FALSE)
    if(APPLE)
        set(PLATFORM_ENV "xcode")
        set(CMAKE_MACOSX_RPATH 1)
    else()
        set(PLATFORM_ENV "msvs")
    endif()
endif()